CREATE SEQUENCE seq_toc START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_est START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_mun START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_clb START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_mar START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_arm START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE seq_oco START WITH 1 NOCACHE ORDER;
