ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER DW_USER IDENTIFIED BY DW123;

GRANT CONNECT TO DW_USER;

GRANT CREATE SESSION TO DW_USER;
GRANT CREATE TABLE TO DW_USER;
GRANT CREATE VIEW TO DW_USER;
GRANT CREATE MATERIALIZED VIEW TO DW_USER;

GRANT UNLIMITED TABLESPACE TO DW_USER;

GRANT SELECT ON USER_LAB.ARMAS TO DW_USER;
GRANT SELECT ON USER_LAB.CALIBRES TO DW_USER;
GRANT SELECT ON USER_LAB.ESTADOS TO DW_USER;
GRANT SELECT ON USER_LAB.H_ARMAS TO DW_USER;
GRANT SELECT ON USER_LAB.H_CALIBRES TO DW_USER;
GRANT SELECT ON USER_LAB.H_ESTADOS TO DW_USER;
GRANT SELECT ON USER_LAB.H_MARCAS TO DW_USER;
GRANT SELECT ON USER_LAB.H_MUNICIPIOS TO DW_USER;
GRANT SELECT ON USER_LAB.H_OCORRENCIAS TO DW_USER;
GRANT SELECT ON USER_LAB.H_TIPOS_OCORRENCIA TO DW_USER;
GRANT SELECT ON USER_LAB.MARCAS TO DW_USER;
GRANT SELECT ON USER_LAB.MUNICIPIOS TO DW_USER;
GRANT SELECT ON USER_LAB.OCORRENCIAS TO DW_USER;
GRANT SELECT ON USER_LAB.TIPOS_OCORRENCIA TO DW_USER;
