--Trigger para auditorar historico de armas

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_ARMAS" 
AFTER UPDATE OR DELETE ON H_ARMAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_ARMAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        
        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_ID',:OLD.HARM_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);
    
        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_ESPECIE',:OLD.HARM_ESPECIE,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_MAR_ID',:OLD.HARM_MAR_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_CLB_ID',:OLD.HARM_CLB_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_DATA',:OLD.HARM_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HARM_ID <> :OLD.HARM_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_ID',:OLD.HARM_ID,:NEW.HARM_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HARM_ESPECIE <> :OLD.HARM_ESPECIE) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_ESPECIE',:OLD.HARM_ESPECIE,:NEW.HARM_ESPECIE,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HARM_MAR_ID <> :OLD.HARM_MAR_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_MAR_ID',:OLD.HARM_MAR_ID,:NEW.HARM_MAR_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HARM_CLB_ID <> :OLD.HARM_CLB_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_CLB_ID',:OLD.HARM_CLB_ID,:NEW.HARM_CLB_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HARM_DATA <> :OLD.HARM_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HARM_DATA',:OLD.HARM_DATA,:NEW.HARM_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_ARMAS" ENABLE;


--Trigger para auditorar historico de calibres

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_CALIBRES" 
AFTER UPDATE OR DELETE ON H_CALIBRES
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_CALIBRES';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_ID',:OLD.HCLB_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_DESCRICAO',:OLD.HCLB_DESCRICAO,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_DATA',:OLD.HCLB_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HCLB_ID <> :OLD.HCLB_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_ID',:OLD.HCLB_ID,:NEW.HCLB_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HCLB_DESCRICAO <> :OLD.HCLB_DESCRICAO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_DESCRICAO',:OLD.HCLB_DESCRICAO,:NEW.HCLB_DESCRICAO,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HCLB_DATA <> :OLD.HCLB_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HCLB_DATA',:OLD.HCLB_DATA,:NEW.HCLB_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_CALIBRES" ENABLE;


--Trigger para auditorar historico de estados

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_ESTADOS" 
AFTER UPDATE OR DELETE ON H_ESTADOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_ESTADOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_ID',:OLD.HEST_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_UF',:OLD.HEST_UF,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_DATA',:OLD.HEST_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HEST_ID <> :OLD.HEST_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_ID',:OLD.HEST_ID,:NEW.HEST_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HEST_UF <> :OLD.HEST_UF) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_UF',:OLD.HEST_UF,:NEW.HEST_UF,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HEST_DATA <> :OLD.HEST_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HEST_DATA',:OLD.HEST_DATA,:NEW.HEST_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_ESTADOS" ENABLE;


--Trigger para auditorar historico de marcas

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_MARCA" 
AFTER UPDATE OR DELETE ON H_MARCAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_MARCAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';


        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_ID',:OLD.HMAR_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_NOME',:OLD.HMAR_NOME,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_DATA',:OLD.HMAR_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HMAR_ID <> :OLD.HMAR_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_ID',:OLD.HMAR_ID,:NEW.HMAR_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HMAR_NOME <> :OLD.HMAR_NOME) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_NOME',:OLD.HMAR_NOME,:NEW.HMAR_NOME,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HMAR_DATA <> :OLD.HMAR_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMAR_DATA',:OLD.HMAR_DATA,:NEW.HMAR_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_MARCA" ENABLE;


--Trigger para auditorar historico de municipios

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_MUNICIPIOS" 
AFTER UPDATE OR DELETE ON H_MUNICIPIOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_MUNICIPIOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_ID',:OLD.HMUN_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_NOME',:OLD.HMUN_NOME,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_EST_ID',:OLD.HMUN_EST_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_DATA',:OLD.HMUN_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HMUN_ID <> :OLD.HMUN_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_ID',:OLD.HMUN_ID,:NEW.HMUN_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HMUN_NOME <> :OLD.HMUN_NOME) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_NOME',:OLD.HMUN_NOME,:NEW.HMUN_NOME,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HMUN_EST_ID <> :OLD.HMUN_EST_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_EST_ID',:OLD.HMUN_EST_ID,:NEW.HMUN_EST_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HMUN_DATA <> :OLD.HMUN_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HMUN_DATA',:OLD.HMUN_DATA,:NEW.HMUN_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_MUNICIPIOS" ENABLE;


--Trigger para auditorar historico de ocorrencias

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_OCORRENCIAS" 
AFTER UPDATE OR DELETE ON H_OCORRENCIAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_OCORRENCIAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_ID',:OLD.HOCO_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_MES',:OLD.HOCO_MES,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_ARM_ID',:OLD.HOCO_ARM_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_TOC_ID',:OLD.HOCO_TOC_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_MUN_ID',:OLD.HOCO_MUN_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_DATA',:OLD.HOCO_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HOCO_ID <> :OLD.HOCO_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_ID',:OLD.HOCO_ID,:NEW.HOCO_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HOCO_MES <> :OLD.HOCO_MES) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_MES',:OLD.HOCO_MES,:NEW.HOCO_MES,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HOCO_ARM_ID <> :OLD.HOCO_ARM_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_ARM_ID',:OLD.HOCO_ARM_ID,:NEW.HOCO_ARM_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HOCO_TOC_ID <> :OLD.HOCO_TOC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_TOC_ID',:OLD.HOCO_TOC_ID,:NEW.HOCO_TOC_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HOCO_MUN_ID <> :OLD.HOCO_MUN_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_MUN_ID',:OLD.HOCO_MUN_ID,:NEW.HOCO_MUN_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HOCO_DATA <> :OLD.HOCO_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HOCO_DATA',:OLD.HOCO_DATA,:NEW.HOCO_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_OCORRENCIAS" ENABLE;


--Trigger para auditorar historico de tipos de ocorrencias

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_TIPOS_OCORRENCIAS" 
AFTER UPDATE OR DELETE ON H_TIPOS_OCORRENCIA
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR(30) := 'H_TIPOS_OCORRENCIA';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_ID',:OLD.HTOC_ID,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_DESCRICAO',:OLD.HTOC_DESCRICAO,NULL,V_USU_BD,V_USU_SO,SYSDATE);

        AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_DATA',:OLD.HTOC_DATA,NULL,V_USU_BD,V_USU_SO,SYSDATE);

    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.HTOC_ID <> :OLD.HTOC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_ID',:OLD.HTOC_ID,:NEW.HTOC_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HTOC_DESCRICAO <> :OLD.HTOC_DESCRICAO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_DESCRICAO',:OLD.HTOC_DESCRICAO,:NEW.HTOC_DESCRICAO,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        IF (:NEW.HTOC_DATA <> :OLD.HTOC_DATA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA,V_TP_OPERACAO,'HTOC_DATA',:OLD.HTOC_DATA,:NEW.HTOC_DATA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_TIPOS_OCORRENCIAS" ENABLE;
