CREATE OR REPLACE TRIGGER tg_htoc
BEFORE UPDATE OR DELETE ON TIPOS_OCORRENCIA
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_OCORRENCIA VALUES (:OLD.toc_id,:OLD.toc_descricao, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_hest
BEFORE UPDATE OR DELETE ON ESTADOS
FOR EACH ROW
BEGIN
    INSERT INTO H_ESTADOS VALUES (:OLD.est_id, :OLD.est_uf, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_hmun
BEFORE UPDATE OR DELETE ON MUNICIPIOS
FOR EACH ROW
BEGIN
    INSERT INTO H_MUNICIPIOS VALUES (:OLD.mun_id, :OLD.mun_nome, :OLD.mun_est_id, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_hclb
BEFORE UPDATE OR DELETE ON CALIBRES
FOR EACH ROW
BEGIN
    INSERT INTO H_CALIBRES VALUES (:OLD.clb_id, :OLD.clb_descricao, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_hmar
BEFORE UPDATE OR DELETE ON MARCAS
FOR EACH ROW
BEGIN
    INSERT INTO H_MARCAS VALUES (:OLD.mar_id, :OLD.mar_nome, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_harm
BEFORE UPDATE OR DELETE ON ARMAS
FOR EACH ROW
BEGIN
    INSERT INTO H_ARMAS VALUES (:OLD.arm_id, :OLD.arm_especie, :OLD.arm_mar_id, :OLD.arm_clb_id, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER tg_hoco
BEFORE UPDATE OR DELETE ON OCORRENCIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_OCORRENCIAS VALUES (:OLD.oco_id, :OLD.oco_mes, :OLD.oco_arm_id, :OLD.oco_toc_id, :OLD.oco_mun_id, SYSDATE);
END;
/
